### PR TITLE
Fix save to MAT file

### LINKED ISSUE #83: Save to Matlab doesn't work anymore.
The save function used to work, but does not anymore.

For example, if I try

a = 1;
save(V_bias_meas, filename= "test", format=:matlab)

I get an an error
RROR: MethodError: no method matching raw(::Float64)
Closest candidates are:
  raw(::Union{Quantity{T, 𝐈, U}, Level{L, S, Quantity{T, 𝐈, U}} where {L, S}} where {T, U}) at /Users/admin/.julia/packages/TcpInstruments/TgF34/src/util.jl:14
  raw(::Union{Quantity{T, 𝐋² 𝐌 𝐈⁻¹ 𝐓⁻³, U}, Level{L, S, Quantity{T, 𝐋² 𝐌 𝐈⁻¹ 𝐓⁻³, U}} where {L, S}} where {T, U}) at /Users/admin/.julia/packages/TcpInstruments/TgF34/src/util.jl:15
  raw(::Union{Quantity{T, 𝐓⁻¹, U}, Level{L, S, Quantity{T, 𝐓⁻¹, U}} where {L, S}} where {T, U}) at /Users/admin/.julia/packages/TcpInstruments/TgF34/src/util.jl:16
  ...
Stacktrace:
 [1] _broadcast_getindex_evalf
   @ ./broadcast.jl:648 [inlined]
 [2] _broadcast_getindex
   @ ./broadcast.jl:621 [inlined]
 [3] getindex
   @ ./broadcast.jl:575 [inlined]
 [4] copy
   @ ./broadcast.jl:922 [inlined]
 [5] materialize
   @ ./broadcast.jl:883 [inlined]
 [6] save(data::Matrix{Float64}; filename::String, format::Symbol)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/TgF34/src/util.jl:56
 [7] top-level scope
 
 If I do not put format=:matlab, then it still works.

### PR DESCRIPTION
**Pull request by stevenaleung**
Closes #83

### CODE REVIEW

File: src/util.jl [hunk 1]
```diff
@@ -15,6 +15,7 @@ raw(a::Current)   = Float64(ustrip(uconvert(A, a)))
 raw(a::Voltage)   = Float64(ustrip(uconvert(V, a)))
 raw(a::Frequency) = Float64(ustrip(uconvert(Hz, a)))
 raw(a::Time)      = Float64(ustrip(uconvert(u"s", a)))
+raw(non_unitful_input) = non_unitful_input
```
Comment (mofii) [inline src/util.jl:18]: :)

**Review by mofii — APPROVED** [review]
Nice. I love that it comes with updated unit tests!
