### PR TITLE
Fixed errors due to query timeouts

### LINKED ISSUE #101: get_impedance cannot be run consecutively
### Bug description
get_impedance cannot be run more than one time without a pause or delay. 

### Steps or code to reproduce the behavior
```
using TcpInstruments

ia = initialize(Agilent4294A, "10.1.30.39")
for j = 1:2
     data = get_impedance(ia)
end

ERROR: Query timed out
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] query(instr::TcpInstruments.Instr{Agilent4294A}, message::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/PMJpp/src/instrument.jl:241
 [3] f_query(obj::TcpInstruments.Instr{Agilent4294A}, ins::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/PMJpp/src/instrument.jl:249
 [4] f_query
   @ ~/.julia/packages/TcpInstruments/PMJpp/src/instrument.jl:249 [inlined]
 [5] get_volt_dc
   @ ~/.julia/packages/TcpInstruments/PMJpp/src/impedance_analyzer/all.jl:137 [inlined]
 [6] get_impedance_analyzer_info(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/PMJpp/src/impedance_analyzer/all.jl:6
 [7] get_impedance(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/PMJpp/src/impedance_analyzer/Agilent4294A.jl:68
 [8] top-level scope
   @ ./REPL[15]:2
```

### Versions
TcpInstruments.jl version/commit: v0.9.0 
Julia version: 1.6.3

### LINKED ISSUE #102: Create a `flush()` function that can be used after an error occurs
After an error, the instrument buffer can be filled with incomplete data and/or is out of sync with the query functions. Several calls of `read(instrument)` are needed to flush the buffer

### LINKED ISSUE #103: Sleep required between commands to different instruments
### Bug description
A pause is required between using set_voltage on the PS310 power supply and using another instrument control command. Otherwise you get a timeout error when using the 2nd command. A 1 second pause after setting the voltage prevents the error. 0.5 seconds is not usually enough. The issue does not exist if you repeatedly call set_voltage for the ps310. You get it if, for example, you set the voltage and then use get_impedance. This issue likely exists in some other situations where commands are send to equipment in rapid succession. A similar bug has been reported for sequential calls of get_impedance

### Steps or code to reproduce the behavior
```
using TcpInstruments
using Unitful
Z_analyzer= initialize(Agilent4294A,"10.1.30.39");
ps = initialize(SRSPS310, "10.1.30.37:1234"; GPIB_ID=2)
sleep(1)
Z_data1= get_impedance(Z_analyzer);
set_voltage(ps,10u"V");
sleep(0.1)
Z_data2= get_impedance(Z_analyzer);

ERROR: LoadError: Query timed out
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] query(instr::TcpInstruments.Instr{Agilent4294A}, message::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:234
 [3] f_query(obj::TcpInstruments.Instr{Agilent4294A}, ins::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:242
 [4] f_query
   @ ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:242 [inlined]
 [5] get_volt_dc
   @ ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/all.jl:182 [inlined]
 [6] get_impedance_analyzer_info(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/all.jl:18
 [7] get_impedance(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/Agilent4294A.jl:68
 [8] top-level scope
   @ /Volumes/GoogleDrive/Shared drives/user-Quintin/Julia_Functions/test_script.jl:7
in expression starting at /Volumes/GoogleDrive/Shared drives/user-Quintin/Julia_Functions/test_script.jl:7

ERROR: LoadError: Query timed out
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] query(instr::TcpInstruments.Instr{Agilent4294A}, message::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:234
 [3] f_query(obj::TcpInstruments.Instr{Agilent4294A}, ins::String; timeout::Float64)
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:242
 [4] f_query
   @ ~/.julia/packages/TcpInstruments/K2yi5/src/instrument.jl:242 [inlined]
 [5] get_volt_dc
   @ ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/all.jl:182 [inlined]
 [6] get_impedance_analyzer_info(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/all.jl:18
 [7] get_impedance(ia::TcpInstruments.Instr{Agilent4294A})
   @ TcpInstruments ~/.julia/packages/TcpInstruments/K2yi5/src/impedance_analyzer/Agilent4294A.jl:68
 [8] top-level scope
   @ /Volumes/GoogleDrive/Shared drives/user-Quintin/Julia_Functions/test_script.jl:9
in expression starting at /Volumes/GoogleDrive/Shared drives/user-Quintin/Julia_Functions/test_script.jl:9
```

Quick Fix:
```
using TcpInstruments
using Unitful
Z_analyzer= initialize(Agilent4294A,"10.1.30.39");
ps = initialize(SRSPS310, "10.1.30.37:1234"; GPIB_ID=2)
sleep(1)
Z_data1= get_impedance(Z_analyzer);
set_voltage(ps,10u"V");
sleep(1)
Z_data2= get_impedance(Z_analyzer);
```

### Versions
TcpInstruments.jl version/commit: 0.9.0
Julia version: 1.6.1

### PR DESCRIPTION
**Pull request by stevenaleung**
Closes #101
Closes #102 
Closes #103 

Alternatively, `get_volt_dc()` and `get_volt_ac()` could've been refactored to use `f_query(; timeout=0)`. The current change was made to maintain consistency with the rest of the impedance analyzer `get` functions

### CODE REVIEW

**Comment by stevenaleung** [comment]
@quintinstedman You mentioned in #103 that there were several other cases where a quick succession of commands threw errors. Adding you to this PR to see if they've been resolved

**Comment by quintinstedman** [comment]
@stevenaleung Yes, the issues in #103 have been resolved. I tested running multiple commands in succession with several different instruments and had no problems.

**Review by quintinstedman — APPROVED** [review]
Tested. Works well!

File: src/impedance_analyzer/Agilent4294A.jl [hunk 1]
```diff
@@ -33,7 +33,11 @@ end
 
 Returns oscillator (ac) voltage
 """
-get_volt_ac(i::Instr{Agilent4294A}) = f_query(i, "POWE?") * V
+function get_volt_ac(ia::Instr{Agilent4294A})
+    write(ia, "POWE?")
```
Comment (mofii) [inline src/impedance_analyzer/Agilent4294A.jl:37]: Have we tested/verified that this function grabs the AC value and not the power?

**Review by mofii — APPROVED** [review]
👍

File: src/impedance_analyzer/Agilent4294A.jl (hunk 1 above)
Comment (stevenaleung) [reply src/impedance_analyzer/Agilent4294A.jl:37]: It should be grabbing the correct value. This is from the impedance analyzer manual
image
